#!/bin/bash

install ()
{
    wget https://raw.githubusercontent.com/minterger/herramientas-para-linux/master/proxysocks/socks.sh
    wget https://raw.githubusercontent.com/minterger/herramientas-para-linux/master/proxysocks/proxy.py
}

fun_bar () {
  comando[0]="$1"
  comando[1]="$2"
    (
      [[ -e $HOME/fim ]] && rm $HOME/fim
      [[ ! -d ~/.Menu ]] && rm -rf /bin/menu
      ${comando[0]} > /dev/null 2>&1
      ${comando[1]} > /dev/null 2>&1
      touch $HOME/fim
    ) > /dev/null 2>&1 &
  tput civis
  echo -ne "\033[1;33mESPERE \033[1;37m- \033[1;33m["
  while true; do
     for((i=0; i<18; i++)); do
       echo -ne "\033[1;31m#"
       sleep 0.1s
     done
     [[ -e $HOME/fim ]] && rm $HOME/fim && break
     echo -e "\033[1;33m]"
     sleep 1s
     tput cuu1
     tput dl1
     echo -ne "\033[1;33mESPERE \033[1;37m- \033[1;33m["
  done
  echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
  tput cnorm
}

echo -e "\033[1;32mDescargando Archivos\033[0m"
echo
fun_bar install
echo
echo -e "\033[1;32mPara ejecutar el menu de socks usa:\033[1;31m bash socks.sh\033[0m"

exit